name: waven_app
description: Waven App

dependencies:
  font_awesome_flutter: ^8.0.1
  flutter:
    sdk: flutter

  webfeed: "^0.4.2"

  transparent_image: "^0.1.0"
  flutter_staggered_grid_view: ^0.2.7
  html: ^0.13.3
  cached_network_image: ^0.5.1
  residemenu: ^1.2.5
  image: ^2.0.4
  auto_size_text: ^0.2.0
  intl: ^0.15.7
  intro_slider: ^1.0.7
  flutter_swiper: ^1.1.4
  flutter_slidable: "^0.4.9"
  flip_card: ^0.2.1
  shared_preferences: ^0.4.3
  flutter_sidekick: ^0.1.3
  quiver: ^2.0.1
  flutter_sequence_animation: ^3.0.1
  wave: ^0.0.8
  page_transition: ^1.0.7
  sliver_fab: ^1.0.0
  rubber: ^0.2.4
  flutter_spinkit: ^3.1.0
  photo_view: ^0.1.3
  folding_cell: ^0.1.0
  url_launcher: ^4.0.3
  giffy_dialog: ^1.0.1
  dio: ^1.0.13
  share: ^0.5.3
  transformer_page_view: ^0.1.4
  flutter_range_slider: ^1.0.1
  date_format: ^1.0.6
  esys_flutter_share: ^0.0.7
  gradient_app_bar: ^0.0.1
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: "images/icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 uses-material-design: true
 assets:
     - images/ClassesBg/
     - images/
     - images/ShushusImages/
     - images/background_logo/
     - images/GodIcon/
     - images/ShushusImages/ShushusPortraits/
     - images/ShushusImages/ShushusSkill/
     - images/SpellsImages/
     - images/ShushusImages/ShushusPortraitsWithLogo/


 fonts:
    - family: BebasNeue
      fonts:
          - asset: assets/fonts/BebasNeue_Regular.otf
