name: waven_app
description: Waven App

dependencies:
  font_awesome_flutter: ^7.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/xel.trotteuseagite.jpg
    - images/xel.tenebreuxspectral.png
    - images/xel.synchronisateur.jpg
    - images/splashscreen.jpg
    - images/iop.flamboyant.jpg
