name: waven_app
description: Waven App

dependencies:
  font_awesome_flutter: ^7.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  feedparser: "^0.0.2"
  webfeed: "^0.2.1"
  youtube_api: "^0.2.1"
  transparent_image: ^0.1.0
  flutter_html_view: "^0.3.1"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/splashscreen.jpg
    - assets/HeroesDatas.json
    - assets/SpellsDatas.json
    - images/background_the_game.jpg