name: waven_app
description: Waven App

dependencies:
  font_awesome_flutter: ^8.0.1
  flutter:
    sdk: flutter
  cupertino_icons: "^0.1.2"
  webfeed: "^0.3.0"

  transparent_image: "^0.1.0"
  flutter_html_textview: "^0.2.6"
  flutter_staggered_grid_view: ^0.2.2
  percent_indicator: ^1.0.5
  html: ^0.13.3
  zoomable_image: ^1.2.0
  flutter_webview_plugin: 0.2.0
  cached_network_image: "^0.4.1"
  residemenu: ^1.2.5
  image_picker: ^0.4.10
  image: ^2.0.4
  flutter_speed_dial: ^1.0.8
  flutter_swiper: ^1.1.2
  auto_size_text: ^0.2.0
  intl: ^0.15.7
  intro_slider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:

    - assets/HeroesDatas.json
    - assets/HeroesDatav2.json
    - assets/SpellsDatas.json
    - assets/SpellsDatasV2.json
    - images/
    - images/menu_icons/
    - images/spellmaker_res/