import 'dart:ui';

import 'package:waven_app/models/ShushuOfflineModel.dart';
import 'package:waven_app/models/SkinOfflineModel.dart';

final ShushusItems = <ShushuOfflineModel>[
  new ShushuOfflineModel(
      'Iop',
      919,
      'Le chevalier Iop',
      'images/ShushusImages/ShushusPortraits/iop_1.png',
      'le lore Chavelier',
      Color.fromRGBO(55, 0, 30, 0.9),
      '',
      '+1 PA à votre réserve lorsque vous jouez un compagnon.',
      'images/ShushusImages/ShushusSkill/Heros_chevalierIOP_trancher.png',
      'Inflige 4 dégâts. Coup de Grâce : +2 PA à votre réserve.'),
  new ShushuOfflineModel(
      'Iop',
      534,
      'Le Champion Flamboyant',
      'images/ShushusImages/ShushusPortraits/iop_3.png',
      'le lore Flamboyant',
      Color.fromRGBO(226, 78, 46, 0.9),
      '',
      'Gagne 1 PM pour le tour quand vous jouez un sort Feu.',
      'images/ShushusImages/ShushusSkill/Heros_iop_tournoyeur_tournoiement.png',
      'Vous téléporte sur une case adjacente à un personnage HUILÉ et lui inflige 1 dégât.'),
  new ShushuOfflineModel(
      'Iop',
      143,
      'Le Ténébreux Spectral',
      'images/ShushusImages/ShushusPortraits/iop_4.png',
      'le lore Spectral',
      Color.fromRGBO(33, 77, 99, 0.9),
      '',
      'Coup de Grâce : Une Âme Spectrale alliée est invoquée.',
      'images/ShushusImages/ShushusSkill/Heros_iopspectral_AIR_attaquespectrale.png',
      'Inflige 2 dégâts. Coup de Grâce : Invoque une Âme Spectrale.'),
  new ShushuOfflineModel(
      'Iop',
      497,
      'La Bouvalière',
      'images/ShushusImages/ShushusPortraits/iop_5.png',
      'le lore Bouvalière',
      Color.fromRGBO(207, 55, 135, 0.9),
      '',
      '+1 PA à votre réserve lorsque vous effectuez une charge.',
      'images/ShushusImages/ShushusSkill/Heros_Bouvaliere_charge.png',
      'Charge en ligne et inflige 1 dégât + 2 dégâts par case parcourue.'),
  new ShushuOfflineModel(
      'Iop',
      911,
      'Le Iop Coeur Froid',
      'images/ShushusImages/ShushusPortraits/iop_2.png',
      'le lore Coeur froid',
      Color.fromRGBO(78, 150, 150, 0.9),
      '',
      'Sous 32 PDV, se transforme et devient Inciblable.',
      'images/ShushusImages/ShushusSkill/Heros_Chevalieraucoeurfroid_stalagmite.png',
      'Inflige 2 dégâts. +1 PA à votre réserve si la cible est sous l’état MOUILLÉ.'),
  new ShushuOfflineModel(
      'Xelor',
      193,
      'L\'aiguille du Xelor',
      'images/ShushusImages/ShushusPortraits/xelor_1.png',
      'le lore Aiguille',
      Color.fromRGBO(3, 50, 80, 0.9),
      '',
      '+1 PA à votre réserve lorsque vous lancez un SINISTRO.',
      'images/ShushusImages/ShushusSkill/HEROS_Xelor_accelerateur_permutation2.png',
      'Inflige 3 dégâts.​ +2 à votre jauge EAU si la cible est sous l’état MOUILLÉ.​'),
  new ShushuOfflineModel(
      'Xelor',
      490,
      'Le Synchronisateur',
      'images/ShushusImages/ShushusPortraits/xelor_2.png',
      'le lore Synchronisateur',
      Color.fromRGBO(18, 45, 52, 0.9),
      '',
      '+1 PA​ (Vous jouez avec 7 PA)',
      'images/ShushusImages/ShushusSkill/Heros_Xelor_Synchronisateur_maitrisetemporelle.png',
      'Inflige 2 dégâts. Le prochain sort EAU que vous jouez coûte 1 PA de moins.'),
  new ShushuOfflineModel(
      'Xelor',
      945,
      'La Troteuse Agitée',
      'images/ShushusImages/ShushusPortraits/xelor_3.png',
      'le lore Troteuse',
      Color.fromRGBO(14, 29, 51, 0.9),
      '',
      'A chaque téléportation, inflige les dégâts d’arme à l’ennemi ayant le plus de vie.',
      'images/ShushusImages/ShushusSkill/Heros_Xelor_TROTTEUSEagitee_teleportationacceleree.png',
      'Déplace votre héros de 1 case ou à côté d’un SINISTRO allié. Il gagne 1 AR.'),
  new ShushuOfflineModel(
      'Xelor',
      161,
      'La Régulatrice',
      'images/ShushusImages/ShushusPortraits/xelor_5.png',
      'le lore Régulatrice',
      Color.fromRGBO(94, 176, 180, 0.9),
      '',
      '+1 PA à votre réserve chaque fois que vous gagnez de l’AR​.',
      'images/ShushusImages/ShushusSkill/Heros_XELOR_GUARPAPA_regulation2.png',
      'Inflige 1 dégât​. Votre héros gagne autant d’AR​.'),
  new ShushuOfflineModel(
      'Xelor',
      614,
      'Le Xélor Catalyseur',
      'images/ShushusImages/ShushusPortraits/xelor_4.png',
      'le lore Catalyseur',
      Color.fromRGBO(155, 215, 150, 0.9),
      '',
      '+1 Réserve à chaque fois qu’une EXPLOSION alliée se produit.',
      'images/ShushusImages/ShushusSkill/Heros_XELOR_catalyseur_BOOM2.png',
      '+1 AR à votre héros.​ Vos mécanismes appliquent EXPLOSION. ​'),
//  new ShushuOfflineModel('Sram',620,'L\'Egorgeur Shugen','images/HeroPortraits/Iop-Base-Male-CC.png','le lore sram jaune',Color.fromRGBO(227,182, 40, 0.9),'','','',''),
//  new ShushuOfflineModel('Sram',937,'Le Traqueur Sourokan','images/HeroPortraits/Iop-Base-Male-CC.png','le lore Sram biolet',Color.fromRGBO(85,16,112, 0.9),'','','',''),
//  new ShushuOfflineModel('Osamodas',196,'Pâtre Laineux','images/HeroImages/HeroBackground/Fond_Waven_PC_Osamodas_01.jpg','le lore bouftou',Color.fromRGBO(50, 110, 70, 0.9),'','','',''),
//  new ShushuOfflineModel('Osamodas',995,'L\'Eleveur Zélé','images/HeroImages/HeroBackground/Fond_Waven_PC_Osamodas_02.jpg','le lore tofu',Color.fromRGBO(107, 33, 122, 0.9),'','','',''),
//  new ShushuOfflineModel('Eniripsa',311,'????','images/ShushusPortraitImages/Full_Vertical_311.png','le lore Eni',Color.fromRGBO(107, 33, 122, 0.9),'','','',''),
];

final SkinsItems = <SkinOfflineModel>[
  new SkinOfflineModel('Default', 919, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 0),
  new SkinOfflineModel('Skin 2', 919, 'https://via.placeholder.com/200x100',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 919, 'https://via.placeholder.com/400x230',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 919, 'https://via.placeholder.com/500x300',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 919, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 14.99),
  new SkinOfflineModel('Skin 6', 919, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 14.99),
  new SkinOfflineModel('Default', 534, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', null),
  new SkinOfflineModel('Skin 2', 534, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 534, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 534, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 534, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 16.99),
  new SkinOfflineModel('Skin 4', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 16.99),
  new SkinOfflineModel('Skin 5', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 16.99),
  new SkinOfflineModel('Skin 6', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 17.99),
  new SkinOfflineModel('Skin 4', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 17.99),
  new SkinOfflineModel('Skin 5', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 17.99),
  new SkinOfflineModel('Skin 6', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 23.99),
  new SkinOfflineModel('Skin 6', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 23.99),
  new SkinOfflineModel('Skin 1', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 23.99),
  new SkinOfflineModel('Skin 2', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 6', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 100.99),
  new SkinOfflineModel('Skin 1', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 100.99),
  new SkinOfflineModel('Skin 2', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 100.99),
  new SkinOfflineModel('Skin 3', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 6', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
  new SkinOfflineModel('Skin 3', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
  new SkinOfflineModel('Skin 4', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
  new SkinOfflineModel('Skin 5', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 6', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 1.99),
  new SkinOfflineModel('Skin 3', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 1.99),
  new SkinOfflineModel('Skin 4', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 1.99),
  new SkinOfflineModel('Skin 5', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 6', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 614, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 614, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 614, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 614, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 614, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 52.99),
  new SkinOfflineModel('Skin 1', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 52.99),
  new SkinOfflineModel('Skin 2', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 52.99),
  new SkinOfflineModel('Skin 3', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 6', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 937, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 2', 937, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 3', 937, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 4', 937, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 5', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 6', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 1', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
  new SkinOfflineModel('Skin 5', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
  new SkinOfflineModel('Skin 6', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
];
