import 'dart:ui';

import 'package:waven_app/models/ShushuOfflineModel.dart';
import 'package:waven_app/models/SkinOfflineModel.dart';

final ShushusItems = <ShushuOfflineModel>[
 //Iops

  new ShushuOfflineModel(
      'Iop',
      919,
      'Le chevalier Iop',
      'images/ShushusImages/ShushusPortraits/iop_1.png',
      'le lore Chavelier',
      Color.fromRGBO(55, 0, 30, 0.9),
      '',
      '+1 PA à votre réserve lorsque vous jouez un compagnon.',
      'images/ShushusImages/ShushusSkill/Heros_chevalierIOP_trancher.png',
      'Inflige 4 dégâts. Coup de Grâce : +2 PA à votre réserve.',
    'images/ShushusImages/ShushusPortraitsWithLogo/iop_1.png',),
  new ShushuOfflineModel(
      'Iop',
      534,
      'Le Champion Flamboyant',
      'images/ShushusImages/ShushusPortraits/iop_3.png',
      'le lore Flamboyant',
      Color.fromRGBO(226, 78, 46, 0.9),
      '',
      'Gagne 1 PM pour le tour quand vous jouez un sort Feu.',
      'images/ShushusImages/ShushusSkill/Heros_iop_tournoyeur_tournoiement.png',
      'Vous téléporte sur une case adjacente à un personnage HUILÉ et lui inflige 1 dégât.',
    'images/ShushusImages/ShushusPortraitsWithLogo/iop_3.png',),
  new ShushuOfflineModel(
      'Iop',
      143,
      'Le Ténébreux Spectral',
      'images/ShushusImages/ShushusPortraits/iop_4.png',
      'le lore Spectral',
      Color.fromRGBO(33, 77, 99, 0.9),
      '',
      'Coup de Grâce : Une Âme Spectrale alliée est invoquée.',
      'images/ShushusImages/ShushusSkill/Heros_iopspectral_AIR_attaquespectrale.png',
      'Inflige 2 dégâts. Coup de Grâce : Invoque une Âme Spectrale.',
    'images/ShushusImages/ShushusPortraitsWithLogo/iop_4.png',),
  new ShushuOfflineModel(
      'Iop',
      497,
      'La Bouvalière',
      'images/ShushusImages/ShushusPortraits/iop_5.png',
      'le lore Bouvalière',
      Color.fromRGBO(207, 55, 135, 0.9),
      '',
      '+1 PA à votre réserve lorsque vous effectuez une charge.',
      'images/ShushusImages/ShushusSkill/Heros_Bouvaliere_charge.png',
      'Charge en ligne et inflige 1 dégât + 2 dégâts par case parcourue.',
  'images/ShushusImages/ShushusPortraitsWithLogo/iop_5.png'),
  new ShushuOfflineModel(
      'Iop',
      911,
      'Le Iop Coeur Froid',
      'images/ShushusImages/ShushusPortraits/iop_2.png',
      'le lore Coeur froid',
      Color.fromRGBO(78, 150, 150, 0.9),
      '',
      'Sous 32 PDV, se transforme et devient Inciblable.',
      'images/ShushusImages/ShushusSkill/Heros_Chevalieraucoeurfroid_stalagmite.png',
      'Inflige 2 dégâts. +1 PA à votre réserve si la cible est sous l’état MOUILLÉ.',
  'images/ShushusImages/ShushusPortraitsWithLogo/iop_2.png'),

  //endIops
  //Xelor

  new ShushuOfflineModel(
      'Xelor',
      193,
      'L\'aiguille du Xelor',
      'images/ShushusImages/ShushusPortraits/xelor_1.png',
      'le lore Aiguille',
      Color.fromRGBO(3, 50, 80, 0.9),
      '',
      '+1 PA à votre réserve lorsque vous lancez un SINISTRO.',
      'images/ShushusImages/ShushusSkill/HEROS_Xelor_accelerateur_permutation2.png',
      'Inflige 3 dégâts.​ +2 à votre jauge EAU si la cible est sous l’état MOUILLÉ.​',
    'images/ShushusImages/ShushusPortraitsWithLogo/xelor_1.png',),
  new ShushuOfflineModel(
      'Xelor',
      490,
      'Le Synchronisateur',
      'images/ShushusImages/ShushusPortraits/xelor_2.png',
      'le lore Synchronisateur',
      Color.fromRGBO(18, 45, 52, 0.9),
      '',
      '+1 PA​ (Vous jouez avec 7 PA)',
      'images/ShushusImages/ShushusSkill/Heros_Xelor_Synchronisateur_maitrisetemporelle.png',
      'Inflige 2 dégâts. Le prochain sort EAU que vous jouez coûte 1 PA de moins.',
    'images/ShushusImages/ShushusPortraitsWithLogo/xelor_2.png',),
  new ShushuOfflineModel(
      'Xelor',
      945,
      'La Troteuse Agitée',
      'images/ShushusImages/ShushusPortraits/xelor_3.png',
      'le lore Troteuse',
      Color.fromRGBO(14, 29, 51, 0.9),
      '',
      'A chaque téléportation, inflige les dégâts d’arme à l’ennemi ayant le plus de vie.',
      'images/ShushusImages/ShushusSkill/Heros_Xelor_TROTTEUSEagitee_teleportationacceleree.png',
      'Déplace votre héros de 1 case ou à côté d’un SINISTRO allié. Il gagne 1 AR.',
    'images/ShushusImages/ShushusPortraitsWithLogo/xelor_3.png',),
  new ShushuOfflineModel(
      'Xelor',
      161,
      'La Régulatrice',
      'images/ShushusImages/ShushusPortraits/xelor_5.png',
      'le lore Régulatrice',
      Color.fromRGBO(94, 176, 180, 0.9),
      '',
      '+1 PA à votre réserve chaque fois que vous gagnez de l’AR​.',
      'images/ShushusImages/ShushusSkill/Heros_XELOR_GUARPAPA_regulation2.png',
      'Inflige 1 dégât​. Votre héros gagne autant d’AR​.',
  'images/ShushusImages/ShushusPortraitsWithLogo/xelor_5.png'),
  new ShushuOfflineModel(
      'Xelor',
      614,
      'Le Xélor Catalyseur',
      'images/ShushusImages/ShushusPortraits/xelor_4.png',
      'le lore Catalyseur',
      Color.fromRGBO(155, 215, 150, 0.9),
      '',
      '+1 Réserve à chaque fois qu’une EXPLOSION alliée se produit.',
      'images/ShushusImages/ShushusSkill/Heros_XELOR_catalyseur_BOOM2.png',
      '+1 AR à votre héros.​ Vos mécanismes appliquent EXPLOSION. ​',
      'images/ShushusImages/ShushusPortraitsWithLogo/xelor_4.png'),

  //endXelor
  //Cra
  new ShushuOfflineModel(
      'Cra',
      712,
      'Le Disciple Shaden',
      'images/ShushusImages/ShushusPortraits/cra_1.png',
      'le lore Shuriken',
      Color(0xFF2D1A52),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
      'images/ShushusImages/ShushusPortraitsWithLogo/cra_1.png'),

  //endCra
  //Eni
  new ShushuOfflineModel(
      'Eni',
      301,
      'le Champion d\'Ambre',
      'images/ShushusImages/ShushusPortraits/eni_1.png',
      'le lore Ambre',
      Color(0xFFAF5906),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
  'images/ShushusImages/ShushusPortraitsWithLogo/eni_1.png'),
  new ShushuOfflineModel(
      'Eni',
      302,
      'NA',
      'images/ShushusImages/ShushusPortraits/eni_2.png',
      'le lore Vampire',
      Color(0xFF953A57),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
  'images/ShushusImages/ShushusPortraitsWithLogo/eni_2.png',),
  new ShushuOfflineModel(
      'Eni',
      303,
      'Eni Classique',
      'images/ShushusImages/ShushusPortraits/eni_3.png',
      'le lore classique',
      Color(0xFFFFE8BD),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
      'images/ShushusImages/ShushusPortraitsWithLogo/eni_3.png'),
  new ShushuOfflineModel(
      'Eni',
      303,
      'Héroine Déphasée',
      'images/ShushusImages/ShushusPortraits/eni_4.png',
      'le lore classique',
      Color(0xFFFFE8BD),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
      'images/ShushusImages/ShushusPortraitsWithLogo/eni_4.png'),

  //endEni
  //Osa

  new ShushuOfflineModel(
      'Osa',
      401,
      'Eleveuse Tofu',
      'images/ShushusImages/ShushusPortraits/osa_1.png',
      'le lore tofu',
      Color(0xFFB11ABE),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
  'images/ShushusImages/ShushusPortraitsWithLogo/osa_1.png'),
  new ShushuOfflineModel(
      'Osa',
      402,
      'Pâtre Laineaux',
      'images/ShushusImages/ShushusPortraits/osa_2.png',
      'le lore laineau',
      Color(0xFF088736),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
  'images/ShushusImages/ShushusPortraitsWithLogo/osa_2.png'),
  new ShushuOfflineModel(
      'Osa',
      403,
      'Osa Craq',
      'images/ShushusImages/ShushusPortraits/osa_3.png',
      'le lore craq',
      Color(0xFFAEDBBD),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
  'images/ShushusImages/ShushusPortraitsWithLogo/osa_3.png'),

  //endOsa
  //Sram
 new ShushuOfflineModel('Sram',
     620,
     'L\'Egorgeur Shugen',
     'images/ShushusImages/ShushusPortraits/sram_4.png',
     'le lore sram jaune',
     Color(0xFFE8C128),
     '',
     'NA',
     'images/ShushusImages/ShushusSkill/default.png',
     'NA​,',
         'images/ShushusImages/ShushusPortraitsWithLogo/sram_4.png'),
 new ShushuOfflineModel('Sram',
     937,
     'Le Traqueur Sourokan',
     'images/ShushusImages/ShushusPortraits/sram_5.png',
     'le lore Sram biolet',
     Color(0xFF570A76),
     '',
     'NA',
     'images/ShushusImages/ShushusSkill/default.png',
     'NA​',
 'images/ShushusImages/ShushusPortraitsWithLogo/sram_5.png'),
  new ShushuOfflineModel('Sram',
      621,
      'Frappeur Kartana',
      'images/ShushusImages/ShushusPortraits/sram_1.png',
      'le lore sram jaune',
      Color(0xFF86AF6B),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
  'images/ShushusImages/ShushusPortraitsWithLogo/sram_1.png'),
  new ShushuOfflineModel('Sram',
      622,
      'Sram Boken',
      'images/ShushusImages/ShushusPortraits/sram_2.png',
      'le lore Sram biolet',
      Color(0xFF3A3935),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
  'images/ShushusImages/ShushusPortraitsWithLogo/sram_2.png'),
  new ShushuOfflineModel('Sram',
      623,
      'Ecorcheur Shugen',
      'images/ShushusImages/ShushusPortraits/sram_3.png',
      'le lore Sram biolet',
      Color(0xFF174F5C),
      '',
      'NA',
      'images/ShushusImages/ShushusSkill/default.png',
      'NA​',
  'images/ShushusImages/ShushusPortraitsWithLogo/sram_3.png'),
];

final SkinsItems = <SkinOfflineModel>[
  new SkinOfflineModel('Default', 919, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 0),
  new SkinOfflineModel('Skin 2', 919, 'https://via.placeholder.com/200x100',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 919, 'https://via.placeholder.com/400x230',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 919, 'https://via.placeholder.com/500x300',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 919, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 14.99),
  new SkinOfflineModel('Skin 6', 919, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 14.99),
  new SkinOfflineModel('Default', 534, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', null),
  new SkinOfflineModel('Skin 2', 534, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 534, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 534, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 534, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 16.99),
  new SkinOfflineModel('Skin 4', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 16.99),
  new SkinOfflineModel('Skin 5', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 16.99),
  new SkinOfflineModel('Skin 6', 143, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 17.99),
  new SkinOfflineModel('Skin 4', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 17.99),
  new SkinOfflineModel('Skin 5', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 17.99),
  new SkinOfflineModel('Skin 6', 497, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 23.99),
  new SkinOfflineModel('Skin 6', 911, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 23.99),
  new SkinOfflineModel('Skin 1', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 23.99),
  new SkinOfflineModel('Skin 2', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 6', 193, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 100.99),
  new SkinOfflineModel('Skin 1', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 100.99),
  new SkinOfflineModel('Skin 2', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 100.99),
  new SkinOfflineModel('Skin 3', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 6', 490, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
  new SkinOfflineModel('Skin 3', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
  new SkinOfflineModel('Skin 4', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
  new SkinOfflineModel('Skin 5', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 6', 945, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 1.99),
  new SkinOfflineModel('Skin 3', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 1.99),
  new SkinOfflineModel('Skin 4', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 1.99),
  new SkinOfflineModel('Skin 5', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 6', 161, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 614, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 614, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 614, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 614, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 614, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 52.99),
  new SkinOfflineModel('Skin 1', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 52.99),
  new SkinOfflineModel('Skin 2', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 52.99),
  new SkinOfflineModel('Skin 3', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 5', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 6', 620, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 937, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 2', 937, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 3', 937, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 4', 937, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 1', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 5', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 6', 196, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 2.99),
  new SkinOfflineModel('Skin 1', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 2', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 3', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 12.99),
  new SkinOfflineModel('Skin 4', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
  new SkinOfflineModel('Skin 5', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
  new SkinOfflineModel('Skin 6', 995, 'https://via.placeholder.com/960x540',
      'https://waven-game.com/fr/jeu/', 4.99),
];
